# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-02-22 07:16
from __future__ import unicode_literals

import core.models.usertypes
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'ai_customers',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('start_at', models.DateTimeField(default=None, null=True)),
                ('minutes', core.models.usertypes.TinyIntegerField(default=0)),
            ],
            options={
                'db_table': 'ai_movies',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('seats', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'ai_rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_id', models.PositiveIntegerField(db_index=True, default=0)),
                ('movie_id', models.PositiveIntegerField(db_index=True, default=0)),
                ('booked_at', models.DateTimeField(default=None, null=True)),
                ('booked_end_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'ai_room_booking',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_id', models.PositiveIntegerField(db_index=True, default=0)),
                ('movie_id', models.PositiveIntegerField(db_index=True, default=0)),
                ('seat_number', models.PositiveIntegerField(default=0)),
                ('customer_id', models.PositiveIntegerField(default=0)),
                ('room_booking_id', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'ai_tickets',
            },
        ),
    ]
