# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-02-22 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200222_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='room_id',
        ),
    ]
