# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-02-22 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200222_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
